version: "3.1"

services:
    dbhost:
        image: mysql:5.7
        restart: on-failure
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: bazaar
            MYSQL_USER: bazaar
            MYSQL_PASSWORD: bazaar
            MYSQL_ROOT_PASSWORD: bazaar
        volumes:
            - ./initdb.d:/docker-entrypoint-initdb.d:ro
    # Redis Server for Cache
    redis-cache:
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - cache:/data

volumes:
    cache:
        driver: local
